# Generated by Django 3.2.25 on 2026-04-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=45)),
                ('reply', models.CharField(max_length=45)),
                ('user_id', models.IntegerField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
    ]
