# Generated by Django 3.2.25 on 2026-04-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=45)),
                ('comment', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
