# Generated by Django 3.2.25 on 2026-04-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=300)),
                ('specialization', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=15)),
                ('availability', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'worker',
                'managed': True,
            },
        ),
    ]
