# Generated by Django 3.2.25 on 2026-04-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bio', models.CharField(blank=True, max_length=205, null=True)),
                ('profile_pic', models.CharField(blank=True, max_length=405, null=True)),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
    ]
